### ISSUE TITLE
I have a question.

### ISSUE THREAD

**Issue by dbdbdee** [bilogic/logitech-unifying-device#3]
Thank you for the great library.
I am not good at English. I ask for your understanding.
When I reconnect the device, the mouse-related packets work well.
However, the keyboard device must be re-paired.
Otherwise, keyboard command is not possible.
Can I get your email address? I want to send you my full source code.

**Comment by bilogic** [comment]
Hi,

Thanks, but can you recreate the problem using this repo?
I currently don't have the bandwidth to read, understand and debug your code.
